name: "Run docker"

on: 
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -t my-app:latest .

      - name: Run container
        run: docker run -d -p 3000:3000 --name my-container my-app

      - name: Wait for container
        run: sleep 5

      - name: Show logs
        run: docker logs my-container